defmodule CookieCloudServer.Adapters.Netscape do
  @doc """
  生成 Netscape HTTP Cookie File 内容字符串
  格式: domain flag path secure expiration name value
  """
  def dump_string(cookies) do
    header = "# Netscape HTTP Cookie File\n# This file is generated by CookieCloud\n\n"

    body =
      cookies
      |> Enum.map(&format_line/1)
      |> Enum.join("\n")

    header <> body
  end

  # 将内容写入临时文件，并返回文件路径，方便 System.cmd 调用
  def dump_to_temp_file(cookies) do
    path = Path.join(System.tmp_dir!(), "cookies_#{System.unique_integer()}.txt")
    File.write!(path, dump_string(cookies))
    path
  end

  defp format_line(c) do
    # Netscape 格式要求 Tab 分隔
    # 1. Domain
    # 2. Flag (TRUE if domain starts with dot)
    # 3. Path
    # 4. Secure (TRUE/FALSE)
    # 5. Expiration (Unix time)
    # 6. Name
    # 7. Value

    domain = Map.get(c, "domain", "")
    flag = if String.starts_with?(domain, "."), do: "TRUE", else: "FALSE"
    path = Map.get(c, "path", "/")
    secure = if Map.get(c, "secure"), do: "TRUE", else: "FALSE"
    expiration = Map.get(c, "expirationDate", 0) |> round() |> to_string()
    name = Map.get(c, "name", "")
    value = Map.get(c, "value", "")

    Enum.join([domain, flag, path, secure, expiration, name, value], "\t")
  end
end
